### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by BetaMaxHeadroom** [herpiko/unk#6]
Hi, 

This looks incredible. I especially like that I can move the TrackPoint module around to where it is most comfortable for me. The UHK seems to only allow you to use your thumb. And, I am too accustomed to using my index finger to change now. 

I see from the picture that F7 does not show up as green. Were you able to get that to work?

I'd really like to support your project. Do you happen to have a site where I could purchase the keyboard and TrackPoint module? My wrists would certainly appreciate it.

**Comment by BetaMaxHeadroom** [comment]
I don't know if this helps, but I felt that I should share

https://www.amazon.com/dp/B09QM5C1GV/ref=cm_sw_r_apan_i_MAAPSAPSFZ2S8PMFVJ79

**Comment by herpiko** [comment]
@BetaMaxHeadroom 

Hi,

Sorry for the late response.

> This looks incredible. I especially like that I can move the TrackPoint module around to where it is most comfortable for me. The UHK seems to only allow you to use your thumb. And, I am too accustomed to using my index finger to change now.

Thank you! The TrackPoint is the hardest part because there are several PCB version of the TrackPoint and I think I'm lucky to get the one that have documentation around the internet. I have a spared TrackPoint PCB with different version around but I have not tried to wiring it into a working device. 

> I see from the picture that F7 does not show up as green. Were you able to get that to work?

All keys were work as intended.

> I'd really like to support your project. Do you happen to have a site where I could purchase the keyboard and TrackPoint module? My wrists would certainly appreciate it.

I think I can help you to build one and I think now is the right time to do this because I'm on my way to rebuild the keyboard (fixing some issue, cutting the new stainless steel plates, and so on).

Please reach me at herpiko@gmail.com for further discussion.
